apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-char-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: big-char-app
  template:
    metadata:
      labels:
        app: big-char-app
    spec:
      containers:
      - name: big-char-app
        image: {{ .Values.containers.imageRepo }}: {{ .Values.containers.imagrTag }}
        # image: liona29/bigchar:1.5
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: 8004
      imagePullSecrets:
       - name: regcred

