apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: big-char
  # namespace: health-check
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: big-char-app
            port:
              number: 8080
status:
  loadBalancer: {}