apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1       #3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 295862277960.dkr.ecr.eu-central-1.amazonaws.com/ariwein:big-char.1
        #116313440999.dkr.ecr.eu-central-1.amazonaws.com/devopsproject
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 8000
      imagePullSecrets:
          - name: regcred